
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
ipv6: false
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7894
  fallback-filter:
    geoip: false
    ipcidr:
    - 240.0.0.0/4
  nameserver:
    - https://puredns.org/dns-query
    - tls://puredns.org:853
  fallback:
    - tcp://108.137.44.39
    - tcp://108.137.44.9
    - 108.137.44.39
    - 108.137.44.9
tun:
  enable: true
  stack: system 
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://108.137.44.39:53
experimental:
  interface-name: en0

proxies:
  - {name: harun Akrab, server: 104.17.3.81, port: 80, type: vmess, uuid: 6a972287-7574-48ad-aca0-3c918f4258b8, sni: idn.evouch77.me, alterId: 0, cipher: auto, tls: , skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: idn.evouch77.me}}}
  - {name: TLS harun Akrab, server: 104.17.3.81, port: 443, type: vmess, uuid: 6a972287-7574-48ad-aca0-3c918f4258b8, sni: idn.evouch77.me, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: idn.evouch77.me}}}
  - {name: harun RG, server: 104.18.3.2, port: 80, type: vmess, uuid: 6a972287-7574-48ad-aca0-3c918f4258b8, sni: idn.evouch77.me, alterId: 0, cipher: auto, tls: , skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: idn.evouch77.me}}}
  - {name: TLS harun RG, server: 104.18.3.2, port: 443, type: vmess, uuid: 6a972287-7574-48ad-aca0-3c918f4258b8, sni: idn.evouch77.me, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: idn.evouch77.me}}}
  - {name: rohman Akrab, server: 104.17.3.81, port: 80, type: vmess, uuid: cd16660b-5350-4f3a-acaf-081ac57105ad, sni: z4.evouch.tech, alterId: 0, cipher: auto, tls: , skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: z4.evouch.tech}}}
  - {name: TLS rohman Akrab, server: 104.17.3.81, port: 443, type: vmess, uuid: cd16660b-5350-4f3a-acaf-081ac57105ad, sni: z4.evouch.tech, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: z4.evouch.tech}}}
  - {name: rohman RG, server: 104.18.3.2, port: 80, type: vmess, uuid: cd16660b-5350-4f3a-acaf-081ac57105ad, sni: z4.evouch.tech, alterId: 0, cipher: auto, tls: , skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: z4.evouch.tech}}}
  - {name: TLS rohman RG, server: 104.18.3.2, port: 443, type: vmess, uuid: cd16660b-5350-4f3a-acaf-081ac57105ad, sni: z4.evouch.tech, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: z4.evouch.tech}}}
  - {name: ulya Akrab, server: 104.17.3.81, port: 80, type: vmess, uuid: 115680ea-41f2-481b-8200-93a9bcc2a373, sni: z4.evouch.tech, alterId: 0, cipher: auto, tls: , skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: z4.evouch.tech}}}
  - {name: TLS ulya Akrab, server: 104.17.3.81, port: 443, type: vmess, uuid: 115680ea-41f2-481b-8200-93a9bcc2a373, sni: z4.evouch.tech, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: z4.evouch.tech}}}
  - {name: ulya RG, server: 104.18.3.2, port: 80, type: vmess, uuid: 115680ea-41f2-481b-8200-93a9bcc2a373, sni: z4.evouch.tech, alterId: 0, cipher: auto, tls: , skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: z4.evouch.tech}}}
  - {name: TLS ulya RG, server: 104.18.3.2, port: 443, type: vmess, uuid: 115680ea-41f2-481b-8200-93a9bcc2a373, sni: z4.evouch.tech, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: z4.evouch.tech}}}
  - {name: maman Akrab, server: 104.17.3.81, port: 2096, type: trojan, password: maman, skip-cert-verify: true, sni: z1.evouch.tech, udp: true, network: ws, ws-opts: {path: /trojango, headers: {Host: z1.evouch.tech}}}
  - {name: maman RG, server: 104.18.3.2, port: 2096, type: trojan, password: maman, skip-cert-verify: true, sni: z1.evouch.tech, udp: true, network: ws, ws-opts: {path: /trojango, headers: {Host: z1.evouch.tech}}}
proxy-groups:
  - name: Rule
    type: select
    proxies:
      - harun Akrab
      - TLS harun Akrab
      - harun RG
      - TLS harun RG
      - rohman Akrab
      - TLS rohman Akrab
      - rohman RG
      - TLS rohman RG
      - ulya Akrab
      - TLS ulya Akrab
      - ulya RG
      - TLS ulya RG
      - maman Akrab
      - maman RG
rules:
 - MATCH,Rule
