
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
ipv6: false
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7894
  fallback-filter:
    geoip: false
    ipcidr:
    - 240.0.0.0/4
  nameserver:
    - https://puredns.org/dns-query
    - tls://puredns.org:853
  fallback:
    - tcp://108.137.44.39
    - tcp://108.137.44.9
    - 108.137.44.39
    - 108.137.44.9
tun:
  enable: true
  stack: system 
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://108.137.44.39:53
experimental:
  interface-name: en0

proxies:
  - {name: abid Akrab, server: 104.17.3.81, port: 80, type: vmess, uuid: fbee2f4b-ba83-4fe4-9575-c85f3eb6ee92, sni: idn.evouch77.me, alterId: 0, cipher: auto, tls: , skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: idn.evouch77.me}}}
  - {name: TLS abid Akrab, server: 104.17.3.81, port: 443, type: vmess, uuid: fbee2f4b-ba83-4fe4-9575-c85f3eb6ee92, sni: idn.evouch77.me, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: idn.evouch77.me}}}
  - {name: abid Opera, server: 104.18.1.171, port: 80, type: vmess, uuid: fbee2f4b-ba83-4fe4-9575-c85f3eb6ee92, sni: idn.evouch77.me, alterId: 0, cipher: auto, tls: , skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: idn.evouch77.me}}}
  - {name: TLS abid Opera, server: 104.18.1.171, port: 443, type: vmess, uuid: fbee2f4b-ba83-4fe4-9575-c85f3eb6ee92, sni: idn.evouch77.me, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: idn.evouch77.me}}}
  - {name: abid byU, server: 162.159.128.79, port: 443, type: vmess, uuid: fbee2f4b-ba83-4fe4-9575-c85f3eb6ee92, sni: idn.evouch77.me, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: idn.evouch77.me}}}
  - {name: abid byu, server: 162.159.128.78, port: 443, type: vmess, uuid: fbee2f4b-ba83-4fe4-9575-c85f3eb6ee92, sni: idn.evouch77.me, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: idn.evouch77.me}}}
  - {name: herza Akrab, server: 104.17.3.81, port: 80, type: vmess, uuid: 5989251b-a5a5-42f8-bae4-d3496508a2de, sni: id-herza1.rajs-vpn.xyz, alterId: 0, cipher: auto, tls: , skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /vmess, headers: {Host: id-herza1.rajs-vpn.xyz}}}
  - {name: TLS herza Akrab, server: 104.17.3.81, port: 443, type: vmess, uuid: 5989251b-a5a5-42f8-bae4-d3496508a2de, sni: id-herza1.rajs-vpn.xyz, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /vmess, headers: {Host: id-herza1.rajs-vpn.xyz}}}
  - {name: herza Opera, server: 104.18.1.171, port: 80, type: vmess, uuid: 5989251b-a5a5-42f8-bae4-d3496508a2de, sni: id-herza1.rajs-vpn.xyz, alterId: 0, cipher: auto, tls: , skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /vmess, headers: {Host: id-herza1.rajs-vpn.xyz}}}
  - {name: TLS herza Opera, server: 104.18.1.171, port: 443, type: vmess, uuid: 5989251b-a5a5-42f8-bae4-d3496508a2de, sni: id-herza1.rajs-vpn.xyz, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /vmess, headers: {Host: id-herza1.rajs-vpn.xyz}}}
  - {name: herza byU, server: 162.159.128.79, port: 443, type: vmess, uuid: fbee2f4b-ba83-4fe4-9575-c85f3eb6ee92, sni: idn.evouch77.me, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: idn.evouch77.me}}}
  - {name: herza byu, server: 162.159.128.78, port: 443, type: vmess, uuid: fbee2f4b-ba83-4fe4-9575-c85f3eb6ee92, sni: idn.evouch77.me, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: idn.evouch77.me}}}
  - {name: rohman Akrab, server: 104.17.3.81, port: 80, type: vmess, uuid: cd16660b-5350-4f3a-acaf-081ac57105ad, sni: z4.evouch.tech, alterId: 0, cipher: auto, tls: , skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: z4.evouch.tech}}}
  - {name: TLS rohman Akrab, server: 104.17.3.81, port: 443, type: vmess, uuid: cd16660b-5350-4f3a-acaf-081ac57105ad, sni: z4.evouch.tech, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: z4.evouch.tech}}}
  - {name: rohman Opera, server: 104.18.1.171, port: 80, type: vmess, uuid: cd16660b-5350-4f3a-acaf-081ac57105ad, sni: z4.evouch.tech, alterId: 0, cipher: auto, tls: , skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: z4.evouch.tech}}}
  - {name: TLS rohman Opera, server: 104.18.1.171, port: 443, type: vmess, uuid: cd16660b-5350-4f3a-acaf-081ac57105ad, sni: z4.evouch.tech, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: z4.evouch.tech}}}
  - {name: rohman byU, server: 162.159.128.79, port: 443, type: vmess, uuid: fbee2f4b-ba83-4fe4-9575-c85f3eb6ee92, sni: idn.evouch77.me, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: idn.evouch77.me}}}
  - {name: rohman byu, server: 162.159.128.78, port: 443, type: vmess, uuid: fbee2f4b-ba83-4fe4-9575-c85f3eb6ee92, sni: idn.evouch77.me, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /v2ray, headers: {Host: idn.evouch77.me}}}
  - {name: fafa Akrab, server: 104.17.3.81, port: 80, type: vmess, uuid: 8d086dbd-f8f4-466f-b430-d0a4fd1414a3, sni: sg-aws1.rajs-vpn.xyz, alterId: 0, cipher: auto, tls: , skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /vmess, headers: {Host: sg-aws1.rajs-vpn.xyz}}}
  - {name: TLS fafa Akrab, server: 104.17.3.81, port: 443, type: vmess, uuid: 8d086dbd-f8f4-466f-b430-d0a4fd1414a3, sni: sg-aws1.rajs-vpn.xyz, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /vmess, headers: {Host: sg-aws1.rajs-vpn.xyz}}}
  - {name: fafa Opera, server: 104.18.1.171, port: 80, type: vmess, uuid: 8d086dbd-f8f4-466f-b430-d0a4fd1414a3, sni: sg-aws1.rajs-vpn.xyz, alterId: 0, cipher: auto, tls: , skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /vmess, headers: {Host: sg-aws1.rajs-vpn.xyz}}}
  - {name: TLS fafa Opera, server: 104.18.1.171, port: 443, type: vmess, uuid: 8d086dbd-f8f4-466f-b430-d0a4fd1414a3, sni: sg-aws1.rajs-vpn.xyz, alterId: 0, cipher: auto, tls: 1, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: /vmess, headers: {Host: sg-aws1.rajs-vpn.xyz}}}
  - {name: maman Akrab, server: 104.17.3.81, port: 443, type: trojan, password: 9b287cf0-1974-4770-ab37-cc1a8c5913fb, skip-cert-verify: true, sni: id-rajasa.rajs-vpn.xyz, udp: true, network: ws, ws-opts: {path: /trojan, headers: {Host: id-rajasa.rajs-vpn.xyz}}}
  - {name: maman Opera, server: 104.18.1.171, port: 443, type: trojan, password: 9b287cf0-1974-4770-ab37-cc1a8c5913fb, skip-cert-verify: true, sni: id-rajasa.rajs-vpn.xyz, udp: true, network: ws, ws-opts: {path: /trojan, headers: {Host: id-rajasa.rajs-vpn.xyz}}}
  - {name: maman byU, server: 162.159.138.79, port: 443, type: trojan, password: 9b287cf0-1974-4770-ab37-cc1a8c5913fb, skip-cert-verify: true, sni: id-rajasa.rajs-vpn.xyz, udp: true, network: ws, ws-opts: {path: /trojan, headers: {Host: id-rajasa.rajs-vpn.xyz}}}
  - {name: maman byu, server: 162.159.128.78, port: 443, type: trojan, password: 9b287cf0-1974-4770-ab37-cc1a8c5913fb, skip-cert-verify: true, sni: id-rajasa.rajs-vpn.xyz, udp: true, network: ws, ws-opts: {path: /trojan, headers: {Host: id-rajasa.rajs-vpn.xyz}}}
proxy-groups:
  - name: Rule
    type: select
    proxies:
      - abid Akrab
      - TLS abid Akrab
      - abid Opera
      - TLS abid Opera
      - abid byU
      - abid byu
      - herza Akrab
      - TLS herza Akrab
      - herza Opera
      - TLS herza Opera
      - herza byU
      - herza byu
      - rohman Akrab
      - TLS rohman Akrab
      - rohman Opera
      - TLS rohman Opera
      - rohman byU
      - rohman byu
      - fafa Akrab
      - TLS fafa Akrab
      - fafa Opera
      - TLS fafa Opera
      - maman Akrab
      - maman Opera
      - maman byU
      - maman byu
rules:
 - MATCH,Rule
